<?php
/*
* -----------------------------------------------------------------------------
*  DefaultSettings.php (DO NOT EDIT THIS FILE; INSTEAD, USE LocalSettings.php)
* -----------------------------------------------------------------------------
*   Default variables definition
*/

/*
* Working directory: used for searching map geojson (AATTbW_GeoJson.json)
*/
$workingdir = "working/";

/* 
* Default DB Settings: It should be overwritten in LocalSettings.php
*/
$dbServer = 'localhost';
$dbPort = 3306;
$dbDatabase = 'db';
$dbUser = 'user';
$dbPass = 'pass';

/*
* SITEMAP: Defines sections and operations tree
*/

/*
* 1. Modules Path: Where modules should be located (operation contents)
*/
$modulesPath = "modules/";

/*
* 2. IdNames: Layer identifier names
*/
$siteMap_IdNames = [
  0 => 'IdSection',
  1 => 'IdOperation'
];

/*
* 3. SiteMap tree
*   Format:
*     - First Layer:
*           $siteMap[IdSection] = [ <Name>, [<Children>] ]
*     - Second Layer:
*           $siteMap[IdSection]['Children'][IdOperation] = [ <Name>, <ModulePath> ]
*/
$siteMap[0] = [
  "Name" => "Inicio",
];
$siteMap[1] = [
  "Name" => 'Soluciones',
  "Children" => [
    0 => [
      "Name" => 'Compartición privada de datos',
    ],
    1 => [
      "Name" => 'Open Data',
    ],
    2 => [
      "Name" => 'Smart City & IoT',
    ]
  ]
];
$siteMap[2] = [
  "Name" => 'Casos de uso',
  "Children" => [
    0 => [
      "Name" => 'Sector público',
    ],
    1 => [
      "Name" => 'Energía',
    ],
    2 => [
      "Name" => 'Movilidad y transporte',
    ],
    3 => [
      "Name" => 'Banca y seguros',
    ],
    4 => [
      "Name" => 'Industria',
    ]
  ]
];
$siteMap[3] = [
  "Name" => 'Conjuntos de datos',
  "Children" => [
    0 => [
      "Name" => 'Recursos por Comunidad Autónoma',
      "ModulePath" => $modulesPath . '/recursos_ccaa.php'
    ],
    1 => [
      "Name" => 'Recursos por Provincia',
      "ModulePath" => $modulesPath . '/recursos_provincia.php'
    ],
    2 => [
      "Name" => 'Buscador de Conjuntos de Datos',
      "ModulePath" => $modulesPath . '/buscador_conjuntodatos.php'
    ],
    3 => [
      "Name" => 'Explorador de recursos',
    ]
  ]
];


define("USU_PASSW", 0);
define("USU_NOMBRE", 1);
define("USU_ROLES", 2);
/*$aUsuarios = array(
  "admin@example.com" => array("pass", "Admin", ["Owner"]),
  "limited@example.com" => array("pass", "Limited User", ["Limited"]),
);*/
$aUsuarios = [];

/*
* Password requirements
*/
define('PASSWD_MIN_LENGTH', 6);
define('PASSWD_MAX_LENGTH', 10);


// Default Role hierarchy based on sitemap
/*
User role is allowed if:
  1.- $roles[IdSection]==true for first layer
  2.- $roles[IdSection][IdOperation]==true for second layer
  3.- $roles[IdSection][IdOperation]['detail']==true for detail view

  NOTES:
    - If endpoint is an array -> Grant by policy
    - 'All' role : is the default role for users with no role assigned
    - 'Owner' role: has no limitations
*/
$roles = array(
  "All" => [ // Can see all except 'detail' in IdSection=3&IdOperation=2
    0 => true,
    1 => true,
    2 => true,
    3 => [
      0 => true,
      1 => true,
      2 => [
        'detail' => false
      ],
      3 => true
    ]
  ],
  "Owner" => true, // All to see everything
  "Limited" => [ // Allowed to see first and last sections
    0 => true,
    1 => [], // Cannot see operations
    2 => [], // Cannot see operations
    3 => [
      0 => true,
      1 => true,
      2 => true,
      3 => false // Cannot see 'Explorador de recursos'
    ]
  ]
);

/*
* Detail View Variables
*/
//$externallinkhost = 'http://aattbw.example.com';
$externallinkhost = null; // Same host used for request
$externallinkpath = dirname($_SERVER['REQUEST_URI']) . "/detail.php"; // Detail view path

// Resolve current host
if (is_null($externallinkhost)) {
  $protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http");
  $externallinkhost = $protocol . "://$_SERVER[HTTP_HOST]";
}
